import http from 'node:http';
import {readFile,writeFile,mkdir,rename,chmod} from 'node:fs/promises';
import {createHash,randomBytes} from 'node:crypto';
import {resolve,extname,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import webpush from 'web-push';
import {cities,getWeather,advice} from './dist/weather.js';
import {chinaClock,due} from './scheduler.mjs';
const root=dirname(fileURLToPath(import.meta.url));const runtime=resolve(process.env.DATA_DIR||resolve(root,'.runtime'));await mkdir(runtime,{recursive:true,mode:0o700});
const dbFile=resolve(runtime,'devices.json');let devices={};try{devices=JSON.parse(await readFile(dbFile,'utf8'))}catch(e){if(e.code!=='ENOENT')throw e}
let queue=Promise.resolve();function save(){const snapshot=JSON.stringify(devices);queue=queue.catch(()=>{}).then(async()=>{await writeFile(dbFile+'.tmp',snapshot,{mode:0o600});await rename(dbFile+'.tmp',dbFile)});return queue}
const ready=!!process.env.VAPID_SUBJECT;let keys;
if(ready){const file=resolve(runtime,'vapid.json');try{keys=JSON.parse(await readFile(file,'utf8'))}catch(e){if(e.code!=='ENOENT')throw e;keys=webpush.generateVAPIDKeys();await writeFile(file,JSON.stringify(keys),{mode:0o600})}webpush.setVapidDetails(process.env.VAPID_SUBJECT,keys.publicKey,keys.privateKey)}
const hash=s=>createHash('sha256').update(s).digest('hex');
function validateSettings(s){if(!s||!cities[s.city]||!/^([01]\d|2[0-3]):[0-5]\d$/.test(s.time)||!['cold','normal','hot'].includes(s.pref)||typeof s.paused!=='boolean')throw Error('invalid settings');return {city:s.city,time:s.time,pref:s.pref,paused:s.paused,configured:true}}
function validateSubscription(s){if(!s?.endpoint||!s.keys)throw Error('invalid subscription');const url=new URL(s.endpoint);const hosts=['fcm.googleapis.com','updates.push.services.mozilla.com','web.push.apple.com'];if(url.protocol!=='https:'||url.username||url.password||url.port||!hosts.some(h=>url.hostname===h||url.hostname.endsWith('.'+h)))throw Error('unsupported push provider');if(!/^[A-Za-z0-9_-]{80,100}$/.test(s.keys.p256dh)||!/^[A-Za-z0-9_-]{20,30}$/.test(s.keys.auth))throw Error('invalid keys');return {endpoint:s.endpoint,keys:{p256dh:s.keys.p256dh,auth:s.keys.auth}}}
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>16384)throw Error('request too large')}return JSON.parse(raw)}
function json(res,status,value){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value))}
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.json':'application/json'};
const rates=new Map();function rate(req){const key=req.socket.remoteAddress;const now=Date.now();const r=rates.get(key);if(!r||r.until<now){rates.set(key,{until:now+60000,count:1});return true}return ++r.count<=30}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){if(!rate(req))return json(res,429,{error:'too many requests'});if(req.method==='POST'){const allowedOrigin=process.env.PUBLIC_ORIGIN||`http://localhost:${process.env.PORT||4174}`;if(req.headers.origin!==allowedOrigin)return json(res,403,{error:'origin denied'});if(!req.headers['content-type']?.startsWith('application/json'))return json(res,415,{error:'JSON required'})}const token=req.headers.authorization?.replace(/^Bearer /,'')||'';const id=hash(token);const record=devices[id];if(req.method==='GET'&&url.pathname==='/api/status')return json(res,200,{ready,publicKey:keys?.publicKey,subscribed:!!record,settings:record?.settings});if(!ready)return json(res,503,{error:'push service not configured'});if(req.method==='POST'&&url.pathname==='/api/subscribe'){const b=await body(req);const subscription=validateSubscription(b.subscription);const settings=validateSettings(b.settings);if(Object.keys(devices).length>=1000&&!record)return json(res,503,{error:'subscription limit'});const nextToken=token&&record?token:randomBytes(32).toString('base64url');const nextId=hash(nextToken);const existing=Object.entries(devices).find(([,d])=>d.subscription.endpoint===subscription.endpoint);if(existing&&existing[0]!==nextId)return json(res,409,{error:'subscription already belongs to another device token'});devices[nextId]={subscription,settings,sentDate:record?.sentDate||'',retryAt:0,lastError:record?.lastError||null};await save();return json(res,200,{token:nextToken})}if(req.method==='POST'&&url.pathname==='/api/settings'){if(!record)return json(res,401,{error:'unknown device'});record.settings=validateSettings(await body(req));await save();return json(res,200,{ok:true})}return json(res,404,{error:'not found'})}if(req.method!=='GET'&&req.method!=='HEAD'){res.writeHead(405);return res.end()}const name=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname).slice(1);if(!['index.html','app.js','weather.js','style.css','favicon.svg','manifest.json','sw.js'].includes(name)){res.writeHead(404);return res.end('Not found')}const data=await readFile(resolve(root,'dist',name));res.writeHead(200,{'Content-Type':types[extname(name)]||'application/octet-stream','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'});res.end(req.method==='HEAD'?undefined:data)}catch(e){json(res,400,{error:'request could not be completed'})}});
let running=false;async function tick(){if(!ready||running)return;running=true;try{const clock=chinaClock();const forecasts=new Map();for(const [id,record]of Object.entries(devices)){if(!due(record,clock))continue;let payload;try{if(!forecasts.has(record.settings.city))forecasts.set(record.settings.city,getWeather(record.settings.city));const d=await forecasts.get(record.settings.city);payload={title:'早上好，今天出门这样准备：',body:advice(d,record.settings.pref,record.settings.time).body}}catch{payload={title:'出门前 · 天气更新失败',body:'今天的天气暂时获取失败，未使用旧预报。出门前请再确认天气，穿衣和随身建议暂不可用。'}}if(!due(record,chinaClock()))continue;try{await webpush.sendNotification(record.subscription,JSON.stringify(payload),{TTL:3600,topic:'chumen-daily',timeout:15000});record.sentDate=clock.date;record.lastError=null;record.retryAt=0}catch(e){if(e.statusCode===404||e.statusCode===410)delete devices[id];else{record.lastError='push failed';record.retryAt=Date.now()+120000}}await save()}}finally{running=false}}
setInterval(()=>{tick().catch(()=>console.error('Daily notification processing failed'))},30000).unref();setInterval(()=>{for(const [key,r]of rates)if(r.until<Date.now())rates.delete(key)},60000).unref();
server.listen(Number(process.env.PORT||4174),'0.0.0.0',()=>{console.log(`Local: http://localhost:${process.env.PORT||4174}`);console.log(`Daily push: ${ready?'configured':'not configured'}`);tick().catch(()=>{})});
